//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System.Globalization;
using System.Resources;

namespace FloorplanAnnotator.Resources
{
    /// <summary>
    ///   A strongly-typed resource class for looking up localized strings.
    /// </summary>
    public static class Strings
    {
        private static ResourceManager? _resourceManager;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        public static ResourceManager ResourceManager
        {
            get
            {
                _resourceManager ??= new ResourceManager(
                    "FloorplanAnnotator.Resources.Strings",
                    typeof(Strings).Assembly);
                return _resourceManager;
            }
        }

        /// <summary>
        ///   Returns the formatted resource string for the specified key.
        /// </summary>
        private static string GetString(string key) =>
            ResourceManager.GetString(key, CultureInfo.CurrentUICulture) ?? key;

        // ── MainWindow ──────────────────────────────────────────────────────────

        public static string MainWindow_Title => GetString(nameof(MainWindow_Title));
        public static string Toolbar_NewProject => GetString(nameof(Toolbar_NewProject));
        public static string Toolbar_NewProject_Tooltip => GetString(nameof(Toolbar_NewProject_Tooltip));
        public static string Toolbar_Delete => GetString(nameof(Toolbar_Delete));
        public static string Toolbar_Delete_Tooltip => GetString(nameof(Toolbar_Delete_Tooltip));
        public static string Projects_Header => GetString(nameof(Projects_Header));
        public static string Project_CreatedAt_Format => GetString(nameof(Project_CreatedAt_Format));
        public static string Canvas_EmptyState => GetString(nameof(Canvas_EmptyState));
        public static string Annotations_Header => GetString(nameof(Annotations_Header));
        public static string Grid_Column_Label => GetString(nameof(Grid_Column_Label));
        public static string Grid_Column_Type => GetString(nameof(Grid_Column_Type));
        public static string Grid_Column_Coordinates => GetString(nameof(Grid_Column_Coordinates));
        public static string Grid_Column_Color => GetString(nameof(Grid_Column_Color));

        // ── CreateProjectView ───────────────────────────────────────────────────

        public static string CreateProject_Title => GetString(nameof(CreateProject_Title));
        public static string CreateProject_NameLabel => GetString(nameof(CreateProject_NameLabel));
        public static string CreateProject_FloorplanLabel => GetString(nameof(CreateProject_FloorplanLabel));
        public static string CreateProject_AnnotationsLabel => GetString(nameof(CreateProject_AnnotationsLabel));
        public static string Browse_Button => GetString(nameof(Browse_Button));
        public static string Create_Button => GetString(nameof(Create_Button));
        public static string Cancel_Button => GetString(nameof(Cancel_Button));

        // ── CreateProjectViewModel ──────────────────────────────────────────────

        public static string BrowseFloorplan_DialogTitle => GetString(nameof(BrowseFloorplan_DialogTitle));
        public static string BrowseFloorplan_Filter => GetString(nameof(BrowseFloorplan_Filter));
        public static string BrowseAnnotations_DialogTitle => GetString(nameof(BrowseAnnotations_DialogTitle));
        public static string BrowseAnnotations_Filter => GetString(nameof(BrowseAnnotations_Filter));
        public static string Error_FloorplanNotFound => GetString(nameof(Error_FloorplanNotFound));
        public static string Error_AnnotationsNotFound => GetString(nameof(Error_AnnotationsNotFound));

        // ── MainViewModel status messages ───────────────────────────────────────

        public static string Status_Ready => GetString(nameof(Status_Ready));
        public static string Status_LoadingProjects => GetString(nameof(Status_LoadingProjects));
        public static string Status_ProjectsLoaded => GetString(nameof(Status_ProjectsLoaded));
        public static string Status_ErrorLoading => GetString(nameof(Status_ErrorLoading));
        public static string Status_SavingProject => GetString(nameof(Status_SavingProject));
        public static string Status_ProjectCreated => GetString(nameof(Status_ProjectCreated));
        public static string Status_ErrorSaving => GetString(nameof(Status_ErrorSaving));
        public static string Status_DeletingProject => GetString(nameof(Status_DeletingProject));
        public static string Status_ProjectDeleted => GetString(nameof(Status_ProjectDeleted));
        public static string Status_ErrorDeleting => GetString(nameof(Status_ErrorDeleting));
        public static string DeleteProject_Confirm => GetString(nameof(DeleteProject_Confirm));
        public static string DeleteProject_Title => GetString(nameof(DeleteProject_Title));
    }
}
